(ns clojurewerkz.crawlista.test.extraction
  (:import [java.net URI URL])
  (:use clojurewerkz.crawlista.extraction
        clojurewerkz.crawlista.url
        clojure.test
        [clojure.pprint :only (pprint)]))

(println (str "Using Clojure version " *clojure-version*))

(deftest test-extract-title
  (is (= "Wired.com" (extract-title (slurp (clojure.java.io/resource "html/example1.html"))))))

(deftest test-extract-body-text
  (is (= 139 (count (extract-body-text (slurp (clojure.java.io/resource "html/example1.html")))))))

(deftest test-extract-body-html
  (is (= 2839 (count (extract-body-html (slurp (clojure.java.io/resource "html/example1.html")))))))


(deftest test-extract-local-urls
  (let [body     (slurp (clojure.java.io/resource "html/example1.html"))
        result   (extract-local-urls body "http://wired.com")]
    (is (= 8 (count result)))
    (is (=
         (sort #{"http://wired.com"
                 "http://wired.com/dangerroom/2011/11/relative"
                 "http://wired.com/dangerroom.html"
                 "http://wired.com/wiredscience/2011/11/absolute-with-www"
                 "http://wired.com/gadgets/news/2011/11/arms-new-tools-make-it-easier-for-android-devs-to-use-native-code.ars?comments=1"
                 "http://wired.com/auth?goauth_start=1&goauth_service=linkedin&goauth_action=login&loc=/?goauth_action=closewindow&type=authenticate"
                 "http://wired.com/www.wired.com/wiredscience/2011/11/link-without-http"
                 "http://wired.com/dangerroom/2011/11/absolute-without-domain"})
         (sort result)))))

(deftest test-extract-local-followable-urls-case-1
  (let [body     (slurp (clojure.java.io/resource "html/example1.html"))
        result   (extract-local-followable-urls body "http://wired.com")]
    (is (= 7 (count result)))
    (is (= (sort #{"http://wired.com"
                   "http://wired.com/wiredscience/2011/11/absolute-with-www"
                   "http://wired.com/www.wired.com/wiredscience/2011/11/link-without-http"
                   "http://wired.com/dangerroom/2011/11/absolute-without-domain"
                   "http://wired.com/dangerroom/2011/11/relative"
                   "http://wired.com/dangerroom.html"
                   "http://wired.com/gadgets/news/2011/11/arms-new-tools-make-it-easier-for-android-devs-to-use-native-code.ars?comments=1"})
           (sort result)))))


(deftest test-extract-local-followable-urls-case-2
  (let [body     (slurp (clojure.java.io/resource "html/arstechnica.com.html"))
        result   (extract-local-followable-urls body "http://arstechnica.com")
        expected #{"http://arstechnica.com"
                   "http://arstechnica.com/apple"
                   "http://arstechnica.com/apple/guides/2011/11/can-the-iphone-4s-replace-a-real-digital-camera-for-many-yes.ars"
                   "http://arstechnica.com/apple/news/2011/12/battery-life-woes-continue-to-plague-iphone-4s-users.ars"
                   "http://arstechnica.com/apple/news/2011/12/it-appears-the-syrian-government.ars?comments=1"
                   "http://arstechnica.com/apple/news/2011/12/mac-os-x-1073-includes.ars?comments=1"
                   "http://arstechnica.com/apple/news/2011/12/thai-flooding-finally-hits-apple-with-2tb-drive-shortage.ars"
                   "http://arstechnica.com/apple/reviews/2011/11/why-steve-jobs-cried.ars"
                   "http://arstechnica.com/ask-ars"
                   "http://arstechnica.com/author/ben-kuchera"
                   "http://arstechnica.com/author/casey-johnston"
                   "http://arstechnica.com/author/chris-foresman"
                   "http://arstechnica.com/author/jacqui-cheng"
                   "http://arstechnica.com/author/john-timmer"
                   "http://arstechnica.com/author/jon-brodkin"
                   "http://arstechnica.com/author/matthew-lasar"
                   "http://arstechnica.com/author/nate-anderson"
                   "http://arstechnica.com/author/ohrmazd"
                   "http://arstechnica.com/author/peter-bright"
                   "http://arstechnica.com/author/ryan-paul"
                   "http://arstechnica.com/author/scott-johnson"
                   "http://arstechnica.com/author/sean-gallagher"
                   "http://arstechnica.com/author/wired-uk"
                   "http://arstechnica.com/author/wiredcom"
                   "http://arstechnica.com/business"
                   "http://arstechnica.com/business/consumerization-of-it"
                   "http://arstechnica.com/business/news/2011/11/bulldozer-server-benchmarks-are-here-and-theyre-a-catastrophe.ars"
                   "http://arstechnica.com/business/news/2011/11/private-app-stores-does-your-company-need-its-own.ars"
                   "http://arstechnica.com/business/news/2011/12/bill-would-end-overtime-pay-requirement-for-many-more-it-workers.ars"
                   "http://arstechnica.com/business/news/2011/12/week-in-it-the-end-of-internal-e-mail-and-tracking-cell-phone-signals.ars"
                   "http://arstechnica.com/civis" "http://arstechnica.com/civis/ucp.php?mode=login&return_to=http%3A%2F%2Farstechnica.com%2Findex.php"
                   "http://arstechnica.com/features"
                   "http://arstechnica.com/gadgets"
                   "http://arstechnica.com/gadgets/news/2011/12/apple-managed-to-extend-the.ars?comments=1"
                   "http://arstechnica.com/gadgets/news/2011/12/mobile-operator-turns-flagship-store-into-androidland.ars"
                   "http://arstechnica.com/gadgets/news/2011/12/rims-troubles-continue-blackberry-playbook-costing-company-485-million.ars"
                   "http://arstechnica.com/gadgets/news/2011/12/the-shards-bleeding-edge-anatomy-of-a-21st-century-skyscraper.ars"
                   "http://arstechnica.com/gadgets/reviews/2011/11/dont-call-it-a-tablet-the-kindle-fire-reviewed.ars"
                   "http://arstechnica.com/gadgets/reviews/2011/11/lean-mean-consuming-machine-reviewing-the-nook-tablet.ars"
                   "http://arstechnica.com/gaming"
                   "http://arstechnica.com/gaming/news/2011/11/2011-childs-play-drive-signed-ultima-halo-360-hardware-aliens-themed-nerf-gun.ars"
                   "http://arstechnica.com/gaming/news/2011/12/drm-free-gaming-distributor-gogcom-trades-convenience-for-safety.ars"
                   "http://arstechnica.com/gaming/news/2011/12/markus-notch-person-steps-down-as-lead-minecraft-developer.ars"
                   "http://arstechnica.com/gaming/news/2011/12/microsofts-bid-to-rule-your-living-room-with-the-xbox-360-begins-tomorrow.ars"
                   "http://arstechnica.com/gaming/reviews/2011/11/modern-warfare-3-single-player-on-pc-the-canonization-of-violence.ars"
                   "http://arstechnica.com/guides"
                   "http://arstechnica.com/hardware"
                   "http://arstechnica.com/media"
                   "http://arstechnica.com/microsoft"
                   "http://arstechnica.com/microsoft/news/2011/12/why-microsoft-should-and-shouldnt-support-the-legacy-windows-desktop-on-arm.ars"
                   "http://arstechnica.com/microsoft/news/2011/12/with-wp7-mango-available-for-all-microsoft-pushes-ahead-with-new-updates.ars"
                   "http://arstechnica.com/open-source"
                   "http://arstechnica.com/reviews"
                   "http://arstechnica.com/science"
                   "http://arstechnica.com/science/news/2011/11/how-the-collapse-of-a-scientific-hypothesis-led-to-a-lawsuit-and-arrest.ars"
                   "http://arstechnica.com/science/news/2011/12/-a-us-house-committee.ars?comments=1"
                   "http://arstechnica.com/science/news/2011/12/-voyager-1-has-confirmed.ars?comments=1"
                   "http://arstechnica.com/science/news/2011/12/new-approach-to-determining-human-impact-on-climate-gives-same-answer.ars"
                   "http://arstechnica.com/science/news/2011/12/new-approach-to-determining-human-impact-on-climate-gives-same-answer.ars/2"
                   "http://arstechnica.com/science/news/2011/12/short-circuiting-the-immune-system-to-block-hiv.ars"
                   "http://arstechnica.com/science/news/2011/12/transparent-crab-shell-holds-the-secret-to-bendable-screens.ars"
                   "http://arstechnica.com/science/news/2011/12/week-in-science-collapsing-ideas-and-long-distance-voyagers.ars"
                   "http://arstechnica.com/security"
                   "http://arstechnica.com/site/tv.ars"
                   "http://arstechnica.com/software"
                   "http://arstechnica.com/staff"
                   "http://arstechnica.com/subscriptions"
                   "http://arstechnica.com/tech-policy"
                   "http://arstechnica.com/tech-policy/news/2011/12/apple-motorola-att-sprint-t-mobile-latest-to-be-sued-over-carrier-iq-tracking.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/carrier-iq-hit-with-privacy-lawsuits-as-more-security-researchers-weigh-in.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/data-caps-a-crude-and-unfair-tool-for-easing-online-congestion.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/fcc-to-probe-san-francisco-subway-cell-phone-interruption-policy.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/gallery-how-the-surveillance-industry-markets-spyware-to-governments.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/setting-intelligent-internet-policy-requires-data-we-dont-have-and-arent-getting.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/suspension-of-disbelief-magicians-friends-targeted-by-new-phishing-scam.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/verizon-snags-36b-worth-of-spectrum-licenses-as-att-hits-fcc-roadbloack.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/week-on-the-web-kindle-vs-nook-att-vs-the-fcc-ie10-vs-windows-7.ars"
                   "http://arstechnica.com/tech-policy/news/2011/12/wikileaks-founder-julian-assange-will.ars?comments=1"
                   "http://arstechnica.com/telecom"
                   "http://arstechnica.com/web"}]
    (is (= 81 (count result)))
    (is (= (sort expected) (sort result)))))


(deftest test-extract-local-followable-urls-case-3
  (let [body     (slurp (clojure.java.io/resource "html/page_in_german.html"))
        result   (extract-local-followable-urls body "http://orceo.com")]
    (is (= 30 (count result)))
    (is (= #{"http://orceo.com/link/232"
             "http://orceo.com/de/orceo/30-home"
             "http://orceo.com/link/233"
             "http://orceo.com/de/bt/188-it-service"
             "http://orceo.com/link/224"
             "http://orceo.com/de/bt/telefonanlagen-%28telekommunikation%29/386-themen-blog"
             "http://orceo.com/de/lt/2-zutrittskontrolle"
             "http://orceo.com/mobile"
             "http://orceo.com/de/lt/1-video%C3%BCberwachung-kamera%C3%BCberwachung"
             "http://orceo.com/de/bt/82-zahlungssysteme-ec-geraete-kartenterminals"
             "http://orceo.com"
             "http://orceo.com/de/bt/484-video%C3%BCberwachung"
             "http://orceo.com/de/orceo/262-news-presse"
             "http://orceo.com/de/impressum/72-home"
             "http://orceo.com/de/orceo/54-kontakt-oeffnungszeiten"
             "http://orceo.com/de/orceo/26-jobs"
             "http://orceo.com/sitemap"
             "http://orceo.com/de/rd/18-home"
             "http://orceo.com/de/bt/telefonanlagen-%28telekommunikation%29/226-tk-produkte"
             "http://orceo.com/de/lt/6-home"
             "http://orceo.com/de/bt/telefonanlagen-%28telekommunikation%29/224-tk-planung"
             "http://orceo.com/de/bt/12-home"
             "http://orceo.com/de/nutzungsbedingungen/75-home"
             "http://orceo.com/de/bt/480-dokumenten-management-system-dms"
             "http://orceo.com/de/bt/7-telefonanlagen-%28telekommunikation%29"
             "http://orceo.com/de/bt/9-netzwerke"
             "http://orceo.com/de/bt/8-it-systeme"
             "http://orceo.com/contact"
             "http://orceo.com/users/sign_in"
             "http://orceo.com/link/231"}
           result))))


(deftest test-extract-local-followable-urls-case-4
  (let [body     (slurp (clojure.java.io/resource "html/wired.com_full.html"))
        result   (extract-local-followable-urls body "http://wired.com")
        expected #{"http://wired.com"
                   "http://wired.com/about/faq"
                   "http://wired.com/about/feedback"
                   "http://wired.com/about/mobile"
                   "http://wired.com/about/press"
                   "http://wired.com/about/rss_feeds"
                   "http://wired.com/about/sitemap"
                   "http://wired.com/about/staff_publishing"
                   "http://wired.com/about/staff_web"
                   "http://wired.com/autopia"
                   "http://wired.com/autopia/2012/03/fisker-calls-foul-on-claim-karma-was-rushed"
                   "http://wired.com/autopia/2012/03/march-madness-for-airplane-geeks"
                   "http://wired.com/autopia/2012/03/mitsubishi-turns-their-evs-into-portable-power-supplies"
                   "http://wired.com/autopia/2012/03/nissan-deltawing"
                   "http://wired.com/autopia/2012/03/porsche-918-spyder-prototype"
                   "http://wired.com/autopia/2012/03/spacex-prepares-for-april-30-launch-to-space-station"
                   "http://wired.com/autopia/2012/03/we-need-an-e-reader-for-car-guys"
                   "http://wired.com/blogs"
                   "http://wired.com/cars"
                   "http://wired.com/cloudline"
                   "http://wired.com/cloudline/2012/03/ceo-dares-microsoft"
                   "http://wired.com/cloudline/2012/03/cloud-jobs-wanted-analytics"
                   "http://wired.com/cloudline/2012/03/cloud-security"
                   "http://wired.com/cloudline/2012/03/jolicloud-me"
                   "http://wired.com/cloudline/2012/03/oracle-loses-speed"
                   "http://wired.com/cloudline/2012/03/snitzer"
                   "http://wired.com/cloudline/2012/03/vmware-wsx"
                   "http://wired.com/culture"
                   "http://wired.com/customerservice"
                   "http://wired.com/dangerroom"
                   "http://wired.com/dangerroom/2012/03/afghanistan-war-a-ok"
                   "http://wired.com/dangerroom/2012/03/darpa-galileo"
                   "http://wired.com/dangerroom/2012/03/darpa-satellites"
                   "http://wired.com/dangerroom/2012/03/haiti-quakes"
                   "http://wired.com/dangerroom/2012/03/inside-special-forces"
                   "http://wired.com/dangerroom/2012/03/killing-chinas-carrier-killer"
                   "http://wired.com/dangerroom/2012/03/ocean-drones"
                   "http://wired.com/dangerroom/2012/03/scared-terrorist"
                   "http://wired.com/entertainment"
                   "http://wired.com/epicenter"
                   "http://wired.com/epicenter/2012/03/apple-goes-blue-chip-with-new-quarterly-shareholder-dividend"
                   "http://wired.com/epicenter/2012/03/ff_facebookipo"
                   "http://wired.com/epicenter/2012/03/ff_hoffman"
                   "http://wired.com/epicenter/2012/03/fun-beats-fugly-why-square-is-still-better-than-paypal"
                   "http://wired.com/epicenter/2012/03/groupon-scheduler-gets-wide-release-for-both-sides-of-the-counter"
                   "http://wired.com/epicenter/2012/03/intuit-gopayment-mobile-donations"
                   "http://wired.com/gadgetlab"
                   "http://wired.com/gadgetlab/2012/03/apple-new-ipad-sales"
                   "http://wired.com/gadgetlab/2012/03/creators-project-san-francisco"
                   "http://wired.com/gadgetlab/2012/03/led-lenser-x21-a-whole-bunch-of-badass-in-brilliant-blinding-light"
                   "http://wired.com/gadgetlab/2012/03/microsof-gaming-eyewear-patent"
                   "http://wired.com/gadgetlab/2012/03/nokia-files-patent-for-haptic-feedback-tattoo"
                   "http://wired.com/gadgetlab/2012/03/reuse-ipad-2-satire"
                   "http://wired.com/gadgetlab/2012/03/show-goes-on-daisey"
                   "http://wired.com/gadgetlab/2012/03/smith-wesson-tactical-pen"
                   "http://wired.com/gadgets"
                   "http://wired.com/gamelife"
                   "http://wired.com/gamelife/2012/03/bioware-mass-effect-3-ending"
                   "http://wired.com/gamelife/2012/03/quantum-conundrum-minecraft"
                   "http://wired.com/gaming"
                   "http://wired.com/geekdad"
                   "http://wired.com/geekdad/2012/03/3m-mobile-projector"
                   "http://wired.com/geekdad/2012/03/5-things-expectant-wife"
                   "http://wired.com/geekdad/2012/03/agad032012"
                   "http://wired.com/geekdad/2012/03/ask-the-pixar-animators"
                   "http://wired.com/geekdad/2012/03/data-mining-and-kids-part-1-thank-goodness-she-didnt-pay-cash"
                   "http://wired.com/geekdad/2012/03/dork-tower-monday-79"
                   "http://wired.com/geekdad/2012/03/enter-geekmoms-video-challenge"
                   "http://wired.com/geekdad/2012/03/five-in-five-five-rockets"
                   "http://wired.com/geekdad/2012/03/geekdad-puzzle-of-the-week-answer-concordia-conundrum"
                   "http://wired.com/geekdad/2012/03/geekdad-puzzle-of-the-week-transcendental-mediation"
                   "http://wired.com/geekdad/2012/03/geekmom-rachel-davis"
                   "http://wired.com/geekdad/2012/03/interview-kermit-and-walter-muppets"
                   "http://wired.com/geekdad/2012/03/ipad-3-name"
                   "http://wired.com/geekdad/2012/03/kinect-rush-family-review"
                   "http://wired.com/geekdad/2012/03/lost-tolkien-m-a-r-barker"
                   "http://wired.com/geekdad/2012/03/make-magazine-beta-team"
                   "http://wired.com/geekdad/2012/03/marvel-headphones"
                   "http://wired.com/geekdad/2012/03/pogo-volume-1"
                   "http://wired.com/geekdad/2012/03/skylanders-accessories"
                   "http://wired.com/geekdad/2012/03/the-avengers-hulk-parody"
                   "http://wired.com/magazine"
                   "http://wired.com/magazine/2012/03/locked-room-mystery-in-san-francisco-pits-players-against-werewolf-incursion"
                   "http://wired.com/magazine/decode"
                   "http://wired.com/magazine/ipad"
                   "http://wired.com/medtech"
                   "http://wired.com/multimedia"
                   "http://wired.com/playbook"
                   "http://wired.com/playbook/2012/03/skaters-brave-breakneck-speeds-on-icy-downhill"
                   "http://wired.com/politics"
                   "http://wired.com/rawfile"
                   "http://wired.com/rawfile/2012/03/photos-of-ocean-community-mix-grit-and-beauty"
                   "http://wired.com/reviews"
                   "http://wired.com/reviews/2012/03/apple-new-ipad"
                   "http://wired.com/reviews/2012/03/telyhd"
                   "http://wired.com/reviews/2012/03/ts_revtechwatches"
                   "http://wired.com/reviews/category/automotive"
                   "http://wired.com/reviews/category/desktops-and-accessories"
                   "http://wired.com/reviews/category/digital-cameras-and-camcorders"
                   "http://wired.com/reviews/category/gaming-gear"
                   "http://wired.com/reviews/category/home-audio-and-video"
                   "http://wired.com/reviews/category/household"
                   "http://wired.com/reviews/category/media-players"
                   "http://wired.com/reviews/category/mobile-audio"
                   "http://wired.com/reviews/category/mobile-phones"
                   "http://wired.com/reviews/category/notebooks-and-accessories"
                   "http://wired.com/reviews/category/roundups"
                   "http://wired.com/reviews/category/software-and-apps"
                   "http://wired.com/reviews/category/sports-and-outdoors"
                   "http://wired.com/reviews/category/tablets-and-ebook-readers"
                   "http://wired.com/reviews/category/televisions"
                   "http://wired.com/science"
                   "http://wired.com/services/corrections"
                   "http://wired.com/services/newsletters"
                   "http://wired.com/software"
                   "http://wired.com/techbiz"
                   "http://wired.com/thisdayintech"
                   "http://wired.com/thisdayintech/2012/03/march-19-1474-venice-enacts-a-patently-original-idea"
                   "http://wired.com/thisdayintech/2012/03/march-20-1800-voltas-battery-shows-potential"
                   "http://wired.com/threatlevel"
                   "http://wired.com/threatlevel/2012/03/acta-congressional-approval"
                   "http://wired.com/threatlevel/2012/03/duqu-mystery-language-solved"
                   "http://wired.com/underwire"
                   "http://wired.com/underwire/2012/03/alt-text-apple-app-apocalpyse"
                   "http://wired.com/underwire/2012/03/bad-brains-documentary-sxsw"
                   "http://wired.com/underwire/2012/03/black-mask-studios-occupy-comics"
                   "http://wired.com/underwire/2012/03/cern-artist-von-bismarck"
                   "http://wired.com/underwire/2012/03/ff_reddit"
                   "http://wired.com/underwire/2012/03/gag-me-with-a-toon"
                   "http://wired.com/underwire/2012/03/joseph-gordon-levitt-channels-bruce-willis-in-time-travel-thriller-looper"
                   "http://wired.com/underwire/2012/03/music-apps-sxs"
                   "http://wired.com/underwire/2012/03/ridley-scott-spills-sensational-prometheus-trailer-teases-sequel"
                   "http://wired.com/underwire/2012/03/terminator-ghostbusters-indiana-jones-animated"
                   "http://wired.com/user/login"
                   "http://wired.com/user/logout"
                   "http://wired.com/video"
                   "http://wired.com/video/latest-videos/latest/1815816633/dark-shadows-trailer/1513090506001"
                   "http://wired.com/wellness"
                   "http://wired.com/wiredenterprise"
                   "http://wired.com/wiredenterprise/2012/03/android-linux"
                   "http://wired.com/wiredenterprise/2012/03/cisco-insiemi"
                   "http://wired.com/wiredenterprise/2012/03/google-miner-helmet"
                   "http://wired.com/wiredenterprise/2012/03/google-parts-ways-with-first-business-apps-czar"
                   "http://wired.com/wiredenterprise/2012/03/mr-linux"
                   "http://wired.com/wiredenterprise/2012/03/saba"
                   "http://wired.com/wiredenterprise/2012/03/seagate-trillion-bits"
                   "http://wired.com/wiredscience"
                   "http://wired.com/wiredscience/2012/03/aint-no-imagine-muscle-people-jonah-lehrer-on-creativity"
                   "http://wired.com/wiredscience/2012/03/apollotovenusandmars"
                   "http://wired.com/wiredscience/2012/03/can-genes-send-you-high-or-low-the-orchid-hypothesis-a-bloom"
                   "http://wired.com/wiredscience/2012/03/climate-opinion-economy"
                   "http://wired.com/wiredscience/2012/03/do-not-be-afraid-of-the-diy-space-parachute-it-might-just-work"
                   "http://wired.com/wiredscience/2012/03/ff_aiclass"
                   "http://wired.com/wiredscience/2012/03/ff_antivirals"
                   "http://wired.com/wiredscience/2012/03/ff_prosthetics"
                   "http://wired.com/wiredscience/2012/03/human-bird-wings"
                   "http://wired.com/wiredscience/2012/03/jupiter-io-moon-map"
                   "http://wired.com/wiredscience/2012/03/laser-nuclear-clock"
                   "http://wired.com/wiredscience/2012/03/neurocritic-asks-does-the-human-dorsal-stream-really-process-elongated-vegetables"
                   "http://wired.com/wiredscience/2012/03/physics-in-a-ups-basketball-commercial"
                   "http://wired.com/wiredscience/2012/03/repost-synophalos-formed-cambrian-conga-lines"
                   "http://wired.com/wiredscience/2012/03/spider-silk-smackdown"
                   "http://wired.com/wiredscience/2012/03/stars-time-lapse-space-station"
                   "http://wired.com/wiredscience/2012/03/tiger-cub-photos"
                   "http://wired.com/wiredscience/2012/03/volcanic-highlights-of-my-field-trip-to-california"
                   "http://wired.com/wiredscience/2012/03/volcanoes-and-hurricanes-mortal-enemies-best-friends"
                   "http://wired.com/wiredscience/2012/03/what-james-cameron-can-expect-at-the-bottom-of-the-ocean"
                   "http://wired.com/wiredscience/science-blogs"}]
    (is (= 168 (count result)))
    (is (= (sort expected) (sort result)))))

(deftest test-extract-local-followable-urls-case-5
  (let [body     (slurp (clojure.java.io/resource "html/wired_com_cars1.html"))
        result   (extract-local-followable-urls body "http://wired.com")
        expected #{"http://wired.com"
                   "http://wired.com/?page=10"
                   "http://wired.com/?page=11"
                   "http://wired.com/?page=12"
                   "http://wired.com/?page=13"
                   "http://wired.com/?page=14"
                   "http://wired.com/?page=15"
                   "http://wired.com/?page=16"
                   "http://wired.com/?page=17"
                   "http://wired.com/?page=18"
                   "http://wired.com/?page=19"
                   "http://wired.com/?page=2"
                   "http://wired.com/?page=20"
                   "http://wired.com/?page=3"
                   "http://wired.com/?page=4"
                   "http://wired.com/?page=5"
                   "http://wired.com/?page=6"
                   "http://wired.com/?page=7"
                   "http://wired.com/?page=8"
                   "http://wired.com/?page=9"
                   "http://wired.com/about/faq"
                   "http://wired.com/about/feedback"
                   "http://wired.com/about/mobile"
                   "http://wired.com/about/press"
                   "http://wired.com/about/rss_feeds"
                   "http://wired.com/about/sitemap"
                   "http://wired.com/about/staff_publishing"
                   "http://wired.com/about/staff_web"
                   "http://wired.com/autopia"
                   "http://wired.com/autopia/2012/02/ferrari-f12berlinetta"
                   "http://wired.com/autopia/2012/02/how-nascar-took-over-twitter"
                   "http://wired.com/autopia/2012/02/now-the-autonomous-quadrotors-can-play-music"
                   "http://wired.com/autopia/2012/03/2012-geneva-motor-show"
                   "http://wired.com/autopia/2012/03/a-turbocharged-porsche-museum-goes-on-the-block"
                   "http://wired.com/autopia/2012/03/battery-boosted-rapid-ev-charging-station-wont-shock-the-electric-grid"
                   "http://wired.com/autopia/2012/03/behind-the-wheel-not-all-distractions-are-equal"
                   "http://wired.com/autopia/2012/03/bentley-exp-95-suv"
                   "http://wired.com/autopia/2012/03/boeings-composite-airliner-wins-top-award"
                   "http://wired.com/autopia/2012/03/ferrari-f12berlinetta-debut"
                   "http://wired.com/autopia/2012/03/ferrari-f12berlinetta-video"
                   "http://wired.com/autopia/2012/03/ford-b-max"
                   "http://wired.com/autopia/2012/03/futuristic-airports-unhindered-with-the-baggage-of-todays-reality"
                   "http://wired.com/autopia/2012/03/infiniti-emerg-e-ev"
                   "http://wired.com/autopia/2012/03/mercedes-benz-classics-center"
                   "http://wired.com/autopia/2012/03/mitsubishi-turns-their-evs-into-portable-power-supplies"
                   "http://wired.com/autopia/2012/03/morgan-plue-e"
                   "http://wired.com/autopia/2012/03/new-diesel-electric-hybrid-ferries-are-a-seagoing-first"
                   "http://wired.com/autopia/2012/03/nissan-deltawing"
                   "http://wired.com/autopia/2012/03/toyota-gt-86"
                   "http://wired.com/autopia/2012/03/valmet-dawn-electric-car"
                   "http://wired.com/autopia/2012/03/video-flying-around-the-world-at-30-miles-per-gallon"
                   "http://wired.com/autopia/2012/03/volt-ampera-europe-car-year"
                   "http://wired.com/blogs"
                   "http://wired.com/cars"
                   "http://wired.com/cloudline"
                   "http://wired.com/culture"
                   "http://wired.com/customerservice"
                   "http://wired.com/dangerroom"
                   "http://wired.com/dangerroom/2012/03/spaceplane-year"
                   "http://wired.com/entertainment"
                   "http://wired.com/epicenter"
                   "http://wired.com/gadgetlab"
                   "http://wired.com/gadgets"
                   "http://wired.com/gamelife"
                   "http://wired.com/gaming"
                   "http://wired.com/geekdad"
                   "http://wired.com/geekdad/2012/03/geeks-inherited-the-earth"
                   "http://wired.com/geekdad/2012/03/start-up-trek-money"
                   "http://wired.com/geekdad/2012/03/start-up-trek-name"
                   "http://wired.com/magazine"
                   "http://wired.com/magazine/decode"
                   "http://wired.com/magazine/ipad"
                   "http://wired.com/medtech"
                   "http://wired.com/multimedia"
                   "http://wired.com/playbook"
                   "http://wired.com/politics"
                   "http://wired.com/rawfile"
                   "http://wired.com/reviews"
                   "http://wired.com/reviews/2012/03/ducati-panigale"
                   "http://wired.com/reviews/2012/03/fisker-karma"
                   "http://wired.com/reviews/2012/03/reviews_electricmotorcycles"
                   "http://wired.com/reviews/category/automotive"
                   "http://wired.com/reviews/category/desktops-and-accessories"
                   "http://wired.com/reviews/category/digital-cameras-and-camcorders"
                   "http://wired.com/reviews/category/gaming-gear"
                   "http://wired.com/reviews/category/home-audio-and-video"
                   "http://wired.com/reviews/category/household"
                   "http://wired.com/reviews/category/media-players"
                   "http://wired.com/reviews/category/mobile-audio"
                   "http://wired.com/reviews/category/mobile-phones"
                   "http://wired.com/reviews/category/notebooks-and-accessories"
                   "http://wired.com/reviews/category/roundups"
                   "http://wired.com/reviews/category/software-and-apps"
                   "http://wired.com/reviews/category/sports-and-outdoors"
                   "http://wired.com/reviews/category/tablets-and-ebook-readers"
                   "http://wired.com/reviews/category/televisions"
                   "http://wired.com/rss/cars.xml"
                   "http://wired.com/science"
                   "http://wired.com/services/corrections"
                   "http://wired.com/services/newsletters"
                   "http://wired.com/software"
                   "http://wired.com/techbiz"
                   "http://wired.com/thisdayintech"
                   "http://wired.com/threatlevel"
                   "http://wired.com/underwire"
                   "http://wired.com/user/login"
                   "http://wired.com/user/logout"
                   "http://wired.com/video"
                   "http://wired.com/wellness"
                   "http://wired.com/wiredenterprise"
                   "http://wired.com/wiredscience"
                   "http://wired.com/wiredscience/science-blogs"}]
    (is (= 112 (count result)))
    (is (= (sort expected) (sort result)))))


(deftest test-extract-local-followable-urls-case-6
  (let [body     (slurp (clojure.java.io/resource "html/wired_com_reviews1.html"))
        result   (extract-local-followable-urls body "http://wired.com")
        expected #{"http://wired.com"
                   "http://wired.com/about/faq"
                   "http://wired.com/about/feedback"
                   "http://wired.com/about/mobile"
                   "http://wired.com/about/press"
                   "http://wired.com/about/rss_feeds"
                   "http://wired.com/about/sitemap"
                   "http://wired.com/about/staff_publishing"
                   "http://wired.com/about/staff_web"
                   "http://wired.com/autopia"
                   "http://wired.com/blogs"
                   "http://wired.com/cars"
                   "http://wired.com/cloudline"
                   "http://wired.com/culture"
                   "http://wired.com/customerservice"
                   "http://wired.com/dangerroom"
                   "http://wired.com/entertainment"
                   "http://wired.com/epicenter"
                   "http://wired.com/gadgetlab"
                   "http://wired.com/gadgets"
                   "http://wired.com/gamelife"
                   "http://wired.com/gaming"
                   "http://wired.com/geekdad"
                   "http://wired.com/magazine"
                   "http://wired.com/magazine/decode"
                   "http://wired.com/magazine/ipad"
                   "http://wired.com/medtech"
                   "http://wired.com/multimedia"
                   "http://wired.com/playbook"
                   "http://wired.com/politics"
                   "http://wired.com/rawfile"
                   "http://wired.com/reviews"
                   "http://wired.com/reviews/2011/11/wishlist2011"
                   "http://wired.com/reviews/2012/02/lytro-camera"
                   "http://wired.com/reviews/2012/03/apple-new-ipad"
                   "http://wired.com/reviews/2012/03/ducati-panigale"
                   "http://wired.com/reviews/2012/03/fisker-karma"
                   "http://wired.com/reviews/2012/03/freebord"
                   "http://wired.com/reviews/2012/03/logitech-cube"
                   "http://wired.com/reviews/2012/03/mix-master-mikes"
                   "http://wired.com/reviews/2012/03/photoshop-touch-app"
                   "http://wired.com/reviews/2012/03/reviews_electricmotorcycles"
                   "http://wired.com/reviews/2012/03/reviews_fetish_traxxas"
                   "http://wired.com/reviews/2012/03/scor-4161"
                   "http://wired.com/reviews/2012/03/sony-tablet-p"
                   "http://wired.com/reviews/2012/03/telyhd"
                   "http://wired.com/reviews/2012/03/ts_revtechwatches"
                   "http://wired.com/reviews/2012/03/wacom-intuos5"
                   "http://wired.com/reviews/author/bbrown028"
                   "http://wired.com/reviews/author/bryan-gardiner"
                   "http://wired.com/reviews/author/christinab"
                   "http://wired.com/reviews/author/christopher-null"
                   "http://wired.com/reviews/author/chuck-squatriglia"
                   "http://wired.com/reviews/author/dan-havlik"
                   "http://wired.com/reviews/author/jackson-lynch"
                   "http://wired.com/reviews/author/john-bradley"
                   "http://wired.com/reviews/author/jon-phillips"
                   "http://wired.com/reviews/author/kbarry1726"
                   "http://wired.com/reviews/author/michael-calore"
                   "http://wired.com/reviews/author/mike_isaac"
                   "http://wired.com/reviews/author/samsmith"
                   "http://wired.com/reviews/author/steven-leckart"
                   "http://wired.com/reviews/author/terrence-russell"
                   "http://wired.com/reviews/category/apps"
                   "http://wired.com/reviews/category/apps/creativity-apps"
                   "http://wired.com/reviews/category/automotive"
                   "http://wired.com/reviews/category/desktops-and-accessories"
                   "http://wired.com/reviews/category/digital-cameras-and-camcorders"
                   "http://wired.com/reviews/category/gaming-gear"
                   "http://wired.com/reviews/category/home-audio-and-video"
                   "http://wired.com/reviews/category/household"
                   "http://wired.com/reviews/category/media-players"
                   "http://wired.com/reviews/category/mobile-audio"
                   "http://wired.com/reviews/category/mobile-phones"
                   "http://wired.com/reviews/category/notebooks-and-accessories"
                   "http://wired.com/reviews/category/roundups"
                   "http://wired.com/reviews/category/software-and-apps"
                   "http://wired.com/reviews/category/sports-and-outdoors"
                   "http://wired.com/reviews/category/tablets-and-ebook-readers"
                   "http://wired.com/reviews/category/televisions"
                   "http://wired.com/reviews/feed"
                   "http://wired.com/reviews/page/2"
                   "http://wired.com/science"
                   "http://wired.com/services/corrections"
                   "http://wired.com/services/newsletters"
                   "http://wired.com/software"
                   "http://wired.com/techbiz"
                   "http://wired.com/thisdayintech"
                   "http://wired.com/threatlevel"
                   "http://wired.com/underwire"
                   "http://wired.com/video"
                   "http://wired.com/wellness"
                   "http://wired.com/wiredenterprise"
                   "http://wired.com/wiredscience"
                   "http://wired.com/wiredscience/science-blogs"}]
    (is (= 95 (count result)))
    (is (= (sort expected) (sort result)))))


(deftest test-extract-local-followable-urls-case-7
  (let [body     (slurp (clojure.java.io/resource "html/case1.html"))
        result   (extract-local-followable-urls body "http://www.iq-shop.de/")
        expected #{"http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=24"
                   "http://iq-shop.de/cast-puzzle-ring-ii.html?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=58"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=27"
                   "http://https//www.iq-shop.de/impressum/?___SID=U"
                   "http://iq-shop.de/remember.html?___SID=U"
                   "http://iq-shop.de/eureka-puzzle-schlussel-labyrinth.html?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=28"
                   "http://iq-shop.de/vortex.html?___SID=U"
                   "http://iq-shop.de/widerruf/?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=17"
                   "https://iq-shop.de/wishlist/?___SID=S"
                   "http://iq-shop.de/eureka-puzzle-globus.html?___SID=U"
                   "http://iq-shop.de/geld-tresor.html?___SID=U"
                   "http://iq-shop.de/iqmino-puzzle.html?___SID=U"
                   "http://iq-shop.de/agb/?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?difficulty=21"
                   "http://iq-shop.de/bestellung/?___SID=U"
                   "https://iq-shop.de/checkout/onepage/?___SID=S"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?difficulty=23"
                   "http://iq-shop.de/denk-knobel.html?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?difficulty=25"
                   "http://iq-shop.de/catalog/seo_sitemap/category/?___SID=U"
                   "http://iq-shop.de/datenschutz/?___SID=U"
                   "http://iq-shop.de/zahlung/?___SID=U"
                   "http://iq-shop.de/lieferung/?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?difficulty=26"
                   "http://iq-shop.de/cublino.html?___SID=U"
                   "http://iq-shop.de/ravensburger-think.html?___SID=U"
                   "http://iq-shop.de/voll-verknotet-knot-so-fast.html?___SID=U"
                   "http://iq-shop.de/eureka-puzzle-oskars-wurfel.html?___SID=U"
                   "http://http//www.iq-shop.de/contacts/?___SID=U"
                   "http://iq-shop.de/ringpuzzle-superior-o.html?___SID=U"
                   "http://iq-shop.de/checkout/cart/?___SID=U"
                   "http://iq-shop.de/memory.html?___SID=U"
                   "http://iq-shop.de/strategiespiele.html?___SID=U"
                   "http://iq-shop.de/puzzles.html?___SID=U" "http://iq-shop.de/iq-mino"
                   "http://iq-shop.de/flotter-vierer.html?___SID=U"
                   "http://http//www.iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=30"
                   "http://iq-shop.de/gutscheine.html/?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=52"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=9"
                   "http://iq-shop.de/about/?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=53"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=20"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=54"
                   "http://iq-shop.de/?___SID=U"
                   "https://iq-shop.de/customer/account/?___SID=S"
                   "http://https//www.iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=57"
                   "http://iq-shop.de/cubiform-stacked-cubes.html?___SID=U"
                   "http://iq-shop.de/markus-hofmann-produkte.html?___SID=U"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=22"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=56"
                   "http://iq-shop.de/home/?___SID=U"}]
    (is (= 55 (count result)))
    (is (= (sort expected) (sort result)))))


(deftest test-extract-local-followable-urls-case-8
  (let [body     (slurp (clojure.java.io/resource "html/case2.html"))
        result   (extract-local-followable-urls body "http://www.iq-shop.de/")
        expected #{"http://http//www.iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=30"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=17"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=20"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=22"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=24"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=27"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=28"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=52"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=53"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=54"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=56"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=58"
                   "http://iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=9"
                   "https://http//https://www.iq-shop.de/catalogsearch/advanced/result/?___SID=U?product_type=57"}]
    (is (= 14 (count result)))
    (is (= (sort expected) (sort result)))))


(deftest test-has-anchor
  (let [body (slurp (clojure.java.io/resource "html/arstechnica.com_full.html"))]
    (is (has-anchor? body "/apple"))
    (is (has-anchor? body "/apple" "Apple"))
    (is (not (has-anchor? body "/apple" "Open Source")))
    (is (has-anchor? body "/open-source" "Open Source"))
    (is (has-anchor? body "http://www.wired.com" "Wired"))
    (is (has-anchor? body "http://www.style.com" "Style"))))
